name: Test
on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.18'

      - name: Bootstrap tools
        run: make bootstrap-tools

      - name: Run linters
        run: make lint

      - name: Run tests
        run: make test
